### Find All Jobs
http://localhost:3000/api/v1/jobs

### Find One Job by ID
http://localhost:3000/api/v1/jobs/2

### Search Jobs by Term
http://localhost:3000/api/v1/jobs/search?term=sanar atendente vendedor
